DROP TABLE USER;
CREATE TABLE USER (
ID VARCHAR (10) NOT NULL,
USERNAME VARCHAR (20) NOT NULL,
PASSWORD VARCHAR (20) NOT NULL,
PRIMARY KEY (ID)
);

DROP TABLE POSTS;

CREATE TABLE POSTS (
ID VARCHAR (10) NOT NULL,
CONTENT VARCHAR (200) NOT NULL,
LIKES INT,
PRIMARY KEY (ID)
);